import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { AddBtn, CancelBtn } from '../components/Buttons'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ClientLayout({ children }) {
  return (
          <div className='grid grid-flow-row h-screen grid-rows-24 grid-cols-24'>

            <div className='row-start-1 row-end-4 col-span-24'>
              <Navbar />
            </div>
            <div className='flex flex-col row-start-4 justify-center col-span-24 row-end-15'>   {children}
            </div>
            <div className='flex flex-col gap-5 justify-end items-center col-span-24 row-start-15 row-end-23'>
              <AddBtn />
              <CancelBtn />          
            </div>
            <div className='col-span-24 row-start-24 row-end-25'>
            <Footer />
            </div>
          </div>
        )
}
