import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='pb-3 m-auto max-w-xl h-screen bg-green-900 bg-opacity-80 md:px-2'>
          <Navbar />
          {children}
        </div>
        </body>
    </html>
  )
}
